# IMPORTANTE: Fue ejecutado desde la raiz del proyecto

# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory src contents into the container at /app/src
COPY src/ /app/src/
# Esto lo hacemos para que el código de main-ej2.py pueda acceder 
# corractamente a el modelo, escalador y json(tienen ruta src)

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r /app/src/requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run main.py when the container launches
CMD ["python", "/app/src/main-ej2.py"]
